services:
  spark-master:
    image: spark-api
    container_name: spark-master
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_EXTRA_CLASSPATH=/opt/spark-extra-jars/postgresql-42.2.18.jar
    volumes:
      - ./clean:/opt/bitnami/spark/data/clean
      - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - /home/ttthuy/spark-jars:/opt/spark-extra-jars
    ports:
      - "8080:8080"
      - "7077:7077"
      - "8000:8000"
    networks:
      - etl_net

  spark-worker:
    image: bitnami/spark:3.3.2
    container_name: spark-worker
    user: root
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_EXTRA_CLASSPATH=/opt/spark-extra-jars/postgresql-42.2.18.jar
    depends_on:
      - spark-master
    volumes:
      - /home/ttthuy/spark-jars:/opt/spark-extra-jars
    networks:
      - etl_net

networks:
  etl_net:
    external: true