version: "3.9"

services:
  airbyte:
    image: airbyte/airbyte-webapp:latest
    container_name: airbyte
    ports:
      - "8000:80"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - etl_net

networks:
  etl_net:
    external: true
